### ISSUE TITLE
Invalid API key

### ISSUE THREAD

**Issue by N4ok1** [RocketGod-git/hackcheck-data-breach-search-discord-bot#1]
2024-10-14 23:47:12,688 - root - ERROR - API Error: Invalid API key.
2024-10-14 23:47:12,689 - root - ERROR - API Response: {'error': 'Invalid API key.'}
2024-10-14 23:47:12,689 - root - ERROR - API Error: Invalid API key.

it tells me my api key is invalid even tho i just refreshed it and copy'd from hackcheck.io
i guess its smth like i didnt subscribe so my API key doesnt have any perms or credit but im not sure so it would be great to get some help

**Comment by RocketGod-git** [comment]
Ya, you need to buy a subscription there or your key won't work.

**Comment by N4ok1** [comment]
oh thank you for the ultra fast reply bro
i was supposing it was it theses service aint never free,
anyway thank bro for your project the bot is so well done and ill think about buying a key
anyway bro keep this up have a great day :D
